### ISSUE TITLE
Final ToDo

### ISSUE THREAD

**Issue by JoshuaBog09** [JoshuaBog09/OffShoreWind_Project#4]
- [x] Add text to the turbine lines indicating, the turbine Id
- [x] Interesting information, add annual household usage
- [x] Reformate history dialog
